---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600 # An Hour
- name: Install required pkgs for DNS
  apt:
    name: ['avahi-daemon', 'libnss-mdns']
    state: latest